# ----------------------------------------------------------------------------
# aurora_loopback.xdc
#
# Pin and timing constraints for the standalone Aurora 8B/10B loopback
# bitstream on KR260. Paired with scripts/vivado/build_aurora_loopback.tcl.
#
# Authoritative source for every PACKAGE_PIN / frequency value below is
# top.xsa/design_1.hwh (extracted from the supplied CHIL bitstream); see
# docs/milestone2/M2-A_auroralink_findings.md \u00a72 and \u00a79.5.
#
# Status: committed but not yet run through Vivado (Vivado is not installed
# on the author's workstation). The first synthesis run will validate that
# the port names below match those generated by the block design wrapper.
# If wrapper port names differ (e.g. board automation renames the refclk
# pair), update the get_ports patterns here -- do not silently delete
# constraints. M2-A \u00a710.4 captures this open item.
# ----------------------------------------------------------------------------

# ----------------------------------------------------------------------------
# GT 125 MHz reference clock -- differential pair on KR260 Quad X0Y1
#
# Source: design_1.hwh
#   C_REFCLK_FREQUENCY = 125
#   PACKAGE_PIN P = Y6   (double-confirmed: XTP685 Kria_K26_SOM_Rev1.xdc
#                        line 285 says Y6 = MGTREFCLK0P_224 = som240_2_c3)
#   PACKAGE_PIN N = Y5   (XTP685 line 284: Y5 = MGTREFCLK0N_224 = som240_2_c4)
# Period = 1 / 125 MHz = 8.000 ns.
#
# !! CRITICAL HARDWARE PRECONDITION (see M2-A doc Gap 10.8) !!
#   Per XTP743 (KR260 Carrier Card Schematic, page 16), the *stock* KR260
#   starter kit carrier card drives som240_2_c3/c4 with a 156.25 MHz LVDS
#   oscillator (intended for 10G Ethernet over SFP+ per UG1092). The 125
#   MHz `create_clock` below therefore only matches:
#     (a) a CUSTOM CHIL carrier card with a 125 MHz oscillator wired to
#         those SOM pins, OR
#     (b) a STOCK KR260 with the GTH_REFCLK0 oscillator physically swapped.
#   Bringing this XDC up on an unmodified stock KR260 will result in
#   either timing-analysis failures (because the actual clock period is
#   6.4 ns, not 8.0 ns) or, if timing passes, a 2.5 Gbps line rate that
#   will not match the RTDS far-end.
#
# Notes:
#   * The KR260 board files (kr260_carrier:1.0) do NOT define a
#     GT_125_REFCLK board interface, so we cannot rely on
#     `apply_bd_automation -rule board` to apply the PACKAGE_PIN
#     constraints. We commit them explicitly here.
#   * Do NOT add IOSTANDARD or DIFF_TERM properties to dedicated GT
#     clock pins; they are GTREFCLK_PAD inputs, not regular IOBs,
#     and Vivado will error if such properties are set.
# ----------------------------------------------------------------------------
set_property PACKAGE_PIN Y6 [get_ports GT_125_REFCLK_clk_p]
set_property PACKAGE_PIN Y5 [get_ports GT_125_REFCLK_clk_n]
# Note (Gap 10.8 resolution): the `create_clock` for this refclk is NOT in
# this static XDC because the period depends on the build configuration:
#
#   125    MHz (production target, custom CHIL carrier) -> 8.000 ns period
#   156.25 MHz (stock KR260 starter kit lab variant)    -> 6.400 ns period
#
# `build_aurora_loopback.tcl` emits the correct `create_clock` constraint
# (matching $aurora_refclk_mhz) into a separate auto-generated XDC.
# This file owns only the PACKAGE_PIN locations, which are identical for
# both configurations (same physical pins on the same SOM connector).

# ----------------------------------------------------------------------------
# GT serial I/O -- TX and RX pin pairs for channel X0Y4 (Quad X0Y1, lane 0).
#
# Channel-0 SOM-level GT pins (per XTP685 Kria_K26_SOM_Rev1.xdc lines 272-280):
#   Package pin   SOM connector pin    Net
#   --------------------------------------------------------------------------
#   W4  (TX P)    som240_2_d9          MGTHTXP0_224
#   W3  (TX N)    som240_2_d10         MGTHTXN0_224
#   Y2  (RX P)    som240_2_b9          MGTHRXP0_224
#   Y1  (RX N)    som240_2_b10         MGTHRXN0_224
#
# KR260 carrier-level routing (per XTP743 schematic page 7):
#   som240_2_b9/b10 (RX) and d9/d10 (TX) route to the SFP+ cage (J23 area).
#
# IMPORTANT:
#   For PMA *near-end* loopback (build_aurora_loopback.tcl ties the
#   loopback port to 3'b010 inside the GTH transceiver), the TX/RX pins
#   do NOT need to be physically wired or have an SFP+ module installed;
#   the GTH internally feeds TX -> RX. The PACKAGE_PIN assignments below
#   are commented out for that reason.
#
#   Uncomment + verify if you remove the near-end PMA loopback constant
#   to drive a real SFP+ module:
#
# set_property PACKAGE_PIN W4 [get_ports SFP0_TX_P]
# set_property PACKAGE_PIN W3 [get_ports SFP0_TX_N]
# set_property PACKAGE_PIN Y2 [get_ports SFP0_RX_P]
# set_property PACKAGE_PIN Y1 [get_ports SFP0_RX_N]

# ----------------------------------------------------------------------------
# False-path / asynchronous clock domains
#
# The Aurora user_clk_out (50 MHz, derived from the link) is asynchronous
# to pl_clk0 (100 MHz from PS). Any clock-domain-crossing path between
# the two domains MUST be done through Vivado IP that handles CDC
# explicitly (axi_fifo_mm_s with independent clocks, axis_data_fifo with
# async option, etc.). The constraints below mark inter-clock paths as
# asynchronous so STA does not chase impossible timing arcs.
#
# This pattern matches the recommendation in PG046 v11.1 \u00a76 ("Constraining
# the Core") for designs that share data between user_clk and any other
# clock domain.
# ----------------------------------------------------------------------------
set_clock_groups -asynchronous \
    -group [get_clocks -of [get_pins zynq_ultra_ps_e_0/pl_clk0]] \
    -group [get_clocks -of [get_pins aurora_8b10b_0/user_clk_out]]

# ----------------------------------------------------------------------------
# (Reserved) ILA / debug constraints
#
# When ILA probes are added per docs/explaination_docs/KR260_auroralink.md
# Part 10 (Step 14), the Hardware Manager auto-inserts the constraints.
# Nothing manual to do here.
# ----------------------------------------------------------------------------
